{{- if .Values.sealedSecrets -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "gowebapp.fullname" . }}-secrets
  namespace: {{ .Release.Namespace | default "gowebapp" }}
  labels:
    {{- include "gowebapp.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.sealedSecrets.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  template:
    metadata:
      name: {{ include "gowebapp.fullname" . }}-secrets
      namespace: {{ .Release.Namespace | default "gowebapp" }}
      labels:
        {{- include "gowebapp.labels" . | nindent 8 }}
    type: Opaque
  encryptedData:
    {{- if .Values.sealedSecrets.mysql.appPassword }}
    mysql-app-password: {{ .Values.sealedSecrets.mysql.appPassword | quote }}
    {{- end }}
    {{- if .Values.sealedSecrets.mysql.rootPassword }}
    mysql-root-password: {{ .Values.sealedSecrets.mysql.rootPassword | quote }}
    {{- end }}
    {{- if .Values.sealedSecrets.session.secretKey }}
    session-secret-key: {{ .Values.sealedSecrets.session.secretKey | quote }}
    {{- end }}
{{- end }}
