apiVersion: v2
name: gowebapp
description: Go Web Application with Sealed Secrets
type: application
version: 1.2.2
appVersion: 1.1.1
keywords:
  - go
  - webapp
  - mysql
  - sealed-secrets
home: https://github.com/mahinraza/gowebapp
maintainers:
  - name: Mahin Raza
    email: mahinraza317@gmail.com

# dependencies:
#   - name: sealed-secrets
#     version: 2.5.19
#     repository: https://charts.bitnami.com/bitnami
#     condition: sealed-secrets.enabled
#     tags:
#       - security
#       - controller