# Global settings
global:
  namespace: gowebapp
  imagePullPolicy: Always

# Application settings
app:
  name: gowebapp
  replicaCount: 2
  image:
    repository: mahinraza556/gowebapp
    tag: "23628467642"
    pullPolicy: Always
  service:
    enabled: true
    type: LoadBalancer
    port: 80
    targetPort: 8080
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi
  env:
    APP_ENV: production
    APP_PORT: "8080"
  securityContext:
    runAsUser: 1001
    runAsNonRoot: true
    fsGroup: 1001


# Database settings
mysql:
  enabled: true
  image: mysql:8.0
  replicaCount: 1
  storage:
    size: 5Gi
    storageClass: ""  # Use default storage class
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  config:
    database: gowebapp
    user: gowebapp
    host: mysql-service
    port: 3306

# ConfigMap settings
configmap:
  server:
    httpPort: 8080
    useHTTP: true
    useHTTPS: false
  session:
    name: gosess
    maxAge: 28800
    secure: false
    httpOnly: true
  view:
    caching: true
    baseURI: /
    extension: tmpl
    folder: template

# Sealed Secrets (encrypted values)
sealedSecrets:
  # These is encrypted with kubeseal with cluster-wide scope
  mysql:
    appPassword: "AgAhcbBDwBdAYX7p0ShHc7TE3BYpzAhu66eSAVz0LS7qjWjs+OMNXeN88/GT8gH58wfoNbNwxw7cb3k8lVhtstUfNo6sJNt29zpE0EFc5tS+CRKBjlfN2uPL0EiuO9Bj2YIEvfc739mPE7lA5kCTcFTQ1rW6hCChHvsNElOIWTZ0/zR+0IeSOhWzKZjgrcEoC7KiRDbo68fk50BNWerUABLXQZIEG8sjd8nCOc0lgWpH1Mh9veLXOSeY4tRBP423KGPh0DnF5hJYa1fuKkW+mSvCL/AgLv7KnmuHjbYrKvf69o4HhC92X37IczsqfPg7NgKTflCLWiU0CBhoV7wUp8jyYob7bT+4yfeZFtPS9DsxuI9Uj/4KdpTkr0/9bLo755PNO+ZnK2pYePK/qLp3uREKAJcV3Kbh9SNoOlCH5uYOkVh4hcVk7bEXqajIYcva2Dkr0KdsX2VD5YnQRx6dlyzv6cbF4Iv4ip2FT6jsKrgZJiLA7YQtn9osHLB58yBMop+U41aN1iJnyzKAEzPJ8ls9QwgRRslReCJuNWGztafn57fIoM+VdR0zHKZm2NBx/nfQbwNOsRnXXohoug3LejQhPQj8AFqsE6sU3Wuo8zb81P0glC4M1kWTv0mR6FUtESQORHyzCuYtInA0a++5q84yFSoiZZ3f5RuWAeUpgeYyF2z8fOUmyqzBzj5BFmUTGRhkFo+R22Z2+vKn22vXuMg="  # Will be encrypted
    rootPassword: "AgCANwnjZd1OWwzeBTB95EFrW7G07HJchiyirdyNe2ja+LUFc9c2Wv2u0g8uanOh4QrmN3DnTG7lFp6TluP5vNg6FBQ/U+DmTlomBf84GRsPSMZ/b6oPBD7cTmIiGtzsSIQQVkQO10o/8h5IUmvFZiPoMgMUwFbducie2oDy89LCgBjcNhqID0ppXAGlia9JRdJ0Ma644/w7N/Br5+grx0Y94G/w1zKvSxBtPPbH5hG4y5JBNLCnI19/9pzMMdaIq0yb01u4HRenMN/pfU4kB36QY8KjfdRq4moOCxLp11lI7lU7nZ1fvcUrL0krY97g6u62j5rPcwFpTQyp/+HQnV1g28BK7ljhbNpPIfM6KWtchJdSV0Tq92PCaoRHrPNyILnbWzvHw7jvV/APm6mTI3PiO6x12uBcFqFzohRiIHWmCLpnKhvUTA8JHvrZFk7cIhmcO8U9oVeKamklKbt0pcXafJ/jLJtrZj0Xx1VXBtrv+I746/Jf6IQEwBIjbFPSLEFqwWEsSfz+CKMn3ihEpQVpawC0GCy6NK7fYzADQL8ZVqUtVF8WBcHWKwouHM38z3UdF+wQR35+xQqqH39wcDXvIXfM6Ehfgp/Pc14wsmzgpm+/9dv/FzMnPiX2okGMArET80L9iDHK+GL8f17dTBu8VdjaxOKJ8ZlLDdlbJfq1jvhlhoBtgPZB+fVVhIOyXSAY46qh1lLDaeebRf26wPEJhX9c"  # Will be encrypted
  session:
    secretKey: "AgBU3yp44FpAIVaKdmSibv5G8ILEN5cAaTSdxUv9WguXQYDRQHhPcgYvFo/VXhi5ypLePPv7gvAdCgTjwnwFINSyMe5M5DPHxUuYOQIhH22Y7uKzGcDX569anLuVCFDlfK7Sb3qHMZYiJ8Vq7nIVe+4q4+g9iJn1xY0v9JShoDiz7j80I8/YfL6piR2/bFzWjlzOnAn1YHooSMX8MgePwrq4+rREugGaVwWt9G6mJ1jOfnDSSMVlE03ktIBQt6lXjDf2h/B6NKAuU/cLig96fgXQ9PGzs44TCkkPrFG92z8K+Mj6DFEEVtEZevUcNTnii6l/8t25aiYdhrhyU8cDUpo7kct2z3q4MAoP+GvveaFhQekijY8cy7RPThizEDt4OYOH+dWnE6mrcetaeKRmMLbI9PWEwTmVVFtUXridgl//4jnNIvG7V9gMTINfp79VmPS8JOob7gSCU9i3CiLy41sUyMMMaezDIeaRVWC9NnjhgA6CR7bIJ0DuxVunHA9pscROnRGZJ3vWJnXgsFA12J9JXgviH7B+2wcvt+yI32n+CQO0QA+NJT63hWCML9QWhcbjxpFw2WScsGABkFrNjjgkpyg7q0Bp2JyANigQlydwE6tbJjBTkgha393CZw8765nVGZ6+pB6WRdsSbuVH0WdyUYeKN6PCgltCnn8l4giGgm4X3vdT2BlkbGrLRJDqDu9o/WDtvh7piP2JAIvW4/EcnKDm84WRDA=="  # Will be encrypted
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"

# Network Policy
networkPolicy:
  enabled: true  # Set to false to disable network policies

ingress:
  enabled: true
  ingressClassName: nginx
  sslRedirect: true
  annotations: {}

  hosts:
    - host: gowebapp.mahinraza.online
      paths:
        - path: /
          pathType: Prefix
    - host: api.gowebapp.mahinraza.online
      paths:
        - path: /
          pathType: Prefix

  tls:
    enabled: true
    secretName: gowebapp-tls
    
    # Option 1: Use Cert-Manager (Recommended for production)
    certManager:
      enabled: false
      issuerName: letsencrypt-prod
      duration: 2160h  # 90 days
      renewBefore: 360h  # 15 days
    
    # Option 2: Use Sealed Secret (for imported/self-signed certs)
    sealedSecret:
      enabled: true  # Set to true if not using cert-manager
      cert: "AgDoF3yNoRcsssPCvZ3iSpF6koKMnxDCP8bGt5ai0/1tAB9fRCtXzn9QDlamYG5oxHR/rTH87URbY/wXOY91QK5n9jvC8ffmITmFO05MYwKTlHlLIrSuaTJwUPcyCY2ueSBU1jNKEFfEt5g+vdZLIfB4uYNPOdpdqQ6rBTndLc9O0u8tdwHXNQ8q3TljeXtX8WvDBaIlBPlOUPlTtyhnORq8AvM8oh72CMyZbhvxSyS20eMknMH1e95z9reC0Ja56LvvyN7Y3G40oSGrclmCSUm+fkiXxWegIJe/NRXlPGv8ny3hKvsFPMX0qlfsMex89Q8iEasUZqSjaSfu/GofidJ13fbp1qmAFdMQ7TnFfHfN6wEAOdBe6OcV7Csb1hY/rgpXomL0uIldEeUCP/uQiIHa71RQaLyfYpPwwQLv2OsOBqF+LBM9umM7Z36tVLP9oCcHHNmk3NzyFPyQ3ysgGU6NR4EY0QH0Iv90e6wCSTJjSijJgAPuVHMRCCy2khU3J+/LIJ2gs4wEaMfDDK+4878C2cKulAN1YtTaM7JMMwZBt/bNg+D0/EAwhrGhQmLyHasRr9kqNsx8X5TRq3r1fOfPlf5bGX969sLLdGHxxT6jaZM3v6Shkl5FW5eXn3K6+xlN1xOBw5YH7ZSDBM8pUaEL46UMYTX/OgfNJCXbvHVVAvgtKtvzhXBpogWusbwY3Qi/Mxxz+Y0CeGnRSE601g=="  # Encrypted certificate
      key: "AgCyct/mxL1okzN4s4KoolHtia+++Dctd+wS3y4mav35fi+bPC7CeGQCrtyCbCvrTI99xYclzZPvvSZyKRY0JuYL9z3RRU5ETubMSQe+3bK//pSDNdj67LnrokLeuYaRtHUSq/VpKRec4kh8y8fW3QzLsQRyZzH3JaMqNZxNmdaTVKBar6Ys2urDW7rBLV4uHtdMfM1zHp5DtJ4LBUHjvEyxRVxPss6+8WD/oAYu6lxgM24y9cxLF5inzZMvR4hoXHnc/mVS9Eu4kYf8MnVAtFzlGU+wutln6E3MNRJv2ZxTNb1ysyGQVu1/G/EGffUMXRRkzyAPMsXj7Yw3Np87PmCCQTRq96QIuY3roxojPhK0i2fhNsahPkNO0jFwuVKZDmR+/XKMFOzfsSpv9mqcScH+T9Y/jUfJ7quT9QRqmEIa/AkqnSdOMiQ1ZKqquSBdR4bym1xRK4IftJMHReNCfhCzwGrnzJf7FEunMa/KeOgcVPTWWTMleKvr+xlFqIIieOBfhYM3MDtBEjhKtKEbzHo+7h4aXXM8IRIX++1kFnaw/DnagKhSvzj6oBgXyNcy4B0UGcI9EbdV1e4t2cYYdqfLkCHvg4NU0rEDcZ7i4dZFSMGOhQlxTVNEtLXcystMdf/8sgFDZ7ZqEyWL6i06cDdBwZ1fwOzf1JW2YzYfjtntBug4RqQx0VpvRCaaeAU59Dr17/GrL0MaAvYo+YIE5w=="
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80