{{- if .Values.ingress.certManager.enabled }}
# Let Cert-Manager create the certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "gowebapp.fullname" . }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gowebapp.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.ingress.tls.secretName | default (printf "%s-tls" (include "gowebapp.fullname" .)) }}
  duration: {{ .Values.ingress.certManager.duration | default "2160h" }}
  renewBefore: {{ .Values.ingress.certManager.renewBefore | default "360h" }}
  issuerRef:
    name: {{ .Values.ingress.certManager.issuerName | default "letsencrypt-prod" }}
    kind: ClusterIssuer
  dnsNames:
    {{- range .Values.ingress.hosts }}
    - {{ .host }}
    {{- end }}
{{- end }}