{{- if .Values.externalSecrets.enabled }}
{{- if .Values.externalSecrets.secrets.dbEndpoint.enabled }}
# ExternalSecret for DB Endpoint
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: '{{ include "gowebapp.fullname" . }}{{ .Values.externalSecrets.secrets.dbEndpoint.suffix }}'
  namespace: '{{ .Release.Namespace }}'
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: '{{ .Values.externalSecrets.refreshInterval }}'
  secretStoreRef:
    name: '{{ .Values.externalSecrets.store.name }}'
    kind: '{{ .Values.externalSecrets.store.kind }}'
  target:
    name: '{{ include "gowebapp.fullname" . }}{{ .Values.externalSecrets.secrets.dbEndpoint.suffix }}'
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecrets.secrets.dbEndpoint.keys }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ $.Values.externalSecrets.secrets.dbEndpoint.vaultPath }}
        property: {{ .property }}
    {{- end }}
{{- end }}
{{- end }}