{{- if .Values.ingress.tls.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.ingress.tls.secretName | default (printf "%s-tls" (include "gowebapp.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gowebapp.labels" . | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  template:
    metadata:
      name: {{ .Values.ingress.tls.secretName | default (printf "%s-tls" (include "gowebapp.fullname" .)) }}
      namespace: {{ .Release.Namespace }}
      labels:
        {{- include "gowebapp.labels" . | nindent 8 }}
    type: kubernetes.io/tls
  encryptedData:
    tls.crt: {{ .Values.ingress.tls.sealedSecret.cert | quote }}
    tls.key: {{ .Values.ingress.tls.sealedSecret.key | quote }}
{{- end }}