apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.redis_cart.name }}-service"
  namespace: "{{ .Release.Name }}-{{ .Values.namespace }}-{{ .Values.environment }}"
spec:
  type: ClusterIP
  selector:
    {{- include "common_labels" . | nindent 4 }}
    {{- include "redis_cart_labels" . | nindent 4 }}
  ports:
  - name: tcp-redis
    port: {{ .Values.redis_cart.service.port }}
    targetPort: {{ .Values.redis_cart.service.target_port }}
